### ISSUE TITLE
大佬，可以详细说说手势的边缘限定吗，不太清楚该用那个值去做边缘限定

### ISSUE THREAD

**Issue by weather2rain** [1993hzw/Androids#12]
我感觉这个库很好，手势区分的单指双指操作，缩放也可以控制，就是边缘限定的不知道该用那个值，如果大佬可以把这个写道demo里，或写个博客就很好了

**Comment by 1993hzw** [comment]
要实现边缘拖拽你可以直接使用官方提供的库`ViewDragHelper`

**Comment by weather2rain** [comment]
我看了大佬写的哪个涂鸦项目，但是我这边的需求不太一样，直接使用，感觉有点大了，可能是个人水平问题，代码看的不是很懂，想只要双指缩放移动，单指涂鸦的功能，还有设置背景，背景和画板之间可以加蒙版，我看了大佬的double好像没用的这个库，所以想问一下，可以说一下是怎么去判断边缘的吗？

**Comment by weather2rain** [comment]
我现在用的是TouchGestureDetector,也找到了双指移动的方法onScale,以及双指操作结束的方法，onScaleEnd,我的想法就是我设置缩放倍数是1-5，移动的时候，边缘到了就不动了，不让他还可以继续移动，例如，向右移动，左边边缘贴边了，就不能在向右移动了
