### ISSUE TITLE
ScrollPickerView中的选中监听回调在惯性滑动多次后不会回调？？

### ISSUE THREAD

**Issue by xiaoX3** [1993hzw/Androids#4]
就Demo中的水平滚动的StringScrollPicker在惯性滑动多个后有时不会回调selectlisten。这个bug严重影响使用啊。测试了下，fling超过13、4个item就不会被回调。着急，层主看看。

**Comment by 1993hzw** [comment]
我试了，没出现这种情况呀。

**Comment by xiaoX3** [comment]
我刚又试了下，是会有的，用getSelectPosition是可以获取到正确的，但是每次fling多个之后停下来后有时候回调不会被触发。你多试试，肯定能重现。

**Comment by robinvanPersie** [comment]
我也遇到了这个情况，不清楚要怎么修改。

**Comment by 1993hzw** [comment]
是什么机子上测试的呢

**Comment by robinvanPersie** [comment]
小米4 和 小米note， 好像是moveToCenter() 被return掉了。

**Comment by 1993hzw** [comment]
更新下最新的代码，看问题是否解决了。我这边无法重现，大概看了代码修改了可能有问题的地方。

**Comment by robinvanPersie** [comment]
我确定复现方法了：当我手动滑动item到中间到位置时，就不会触发onfling ,  同时也不会回调监听了。
然后你刚更新code也还是有这个问题，同时又有新的问题了，惯性滑动停止时定位的item不准了，之前没有这个问题。

**Comment by robinvanPersie** [comment]
不用滑动很远，就滑动2，3个item。 比如惯性滑动时你看到2在中间，这时停止滑动后会定位在3

**Comment by 1993hzw** [comment]
你再更新下。忘记删除测试代码了。。。

**Comment by robinvanPersie** [comment]
手动滑动item到中间位置还是不能触发监听，mSelected的值也没有改变。
你看我的图，最上方的picker从2滑动到1了，但是底部蓝色按钮上到总和没变。

![f](https://user-images.githubusercontent.com/10293096/37270283-29005ed2-2609-11e8-9642-20b09dc368ee.png)

**Comment by 1993hzw** [comment]
加我qq:154330138

**Comment by robinvanPersie** [comment]
加了，通过下

**Comment by 1993hzw** [comment]
更新下代码，现在没问题了。原来你没有跑我的demo呀。我一直以为demo有问题。现在你给我看截图，我应该知道是什么问题了
